version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 22

    commands:
      - echo "Installing SSH tools..."
      - apt-get update
      - apt-get install -y openssh-client

  pre_build:
    commands:
      - echo "Fetching SSH key from Secrets Manager..."
      - aws secretsmanager get-secret-value --secret-id taskflow-deploy-key-new --query SecretString --output text > deploy_key.pem

      - echo "Setting permissions..."
      - chmod 400 deploy_key.pem

      - echo "Adding EC2 host to known_hosts..."
      - mkdir -p ~/.ssh
      - ssh-keyscan -H 3.108.120.211 >> ~/.ssh/known_hosts

  build:
    commands:
      - echo "Starting deployment on EC2..."

      - |
        ssh -i deploy_key.pem deploy@3.108.120.211 '
          set -x

          echo "Connected to EC2"

          cd ~/deploy

          echo "Running deploy script..."

          ./deploy.sh
        '

artifacts:
  files:
    - '**/*'