version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 22

    commands:
      - echo "Installing SSH tools..."
      - apt-get update
      - apt-get install -y openssh-client

  pre_build:
    commands:
      - echo "Fetching SSH key from Secrets Manager..."
      - aws secretsmanager get-secret-value --secret-id taskflow-deploy-key --query SecretString --output text > deploy_key.pem

      - chmod 400 deploy_key.pem

      - mkdir -p ~/.ssh
      - ssh-keyscan -H 3.108.120.211 >> ~/.ssh/known_hosts

  build:
    commands:
      - echo "Starting deployment on EC2..."

      - |
        ssh -i deploy_key.pem deploy@3.108.120.211 '
          cd ~/deploy &&
          ./deploy.sh
        '

artifacts:
  files:
    - '**/*'